version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # если Dockerfile для бэкенда лежит в backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production