app = "segment-face"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "echo 'Deployment successful'"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443